### ISSUE TITLE
ERROR 422 (error422) has failed to load correctly

### ISSUE THREAD

**Issue by ripgenius** [Ultreon/ERROR422#4]
java.lang.NoClassDefFoundError: dev/architectury/platform/forge/EventBuses

**Comment by XyperCode** [comment]
You are missing [Architectury API](https://modrinth.com/mod/architectury-api).

**Comment by ripgenius** [comment]
Now I've got java.lang.Error: null

**Comment by XyperCode** [comment]
Are you running it on a server?

**Comment by ripgenius** [comment]
no

**Comment by XyperCode** [comment]
Do you have the full crash file? Or the log?

**Comment by ripgenius** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-03-16 20:15:34
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.3.7-universal.jar%23162!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.3.7-universal.jar%23162!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:438) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23157!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.7.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	ERROR 422 (error422), Version: 0.1.0
		Issue tracker URL: https://github.com/XyperCode/error-422-ported
		at TRANSFORMER/error422@0.1.0/io.github.xypercode.mods.err422.mixin.common.LoadingOverlayAccessor.setLogoBackgroundColor(LoadingOverlayAccessor.java:13)
Stacktrace:
	at io.github.xypercode.mods.err422.mixin.common.LoadingOverlayAccessor.setLogoBackgroundColor(LoadingOverlayAccessor.java:13) ~[error-422-ported-0.1.0%20(1).jar%23155!/:?] {re:classloading}
-- MOD error422 --
Details:
	Mod File: /C:/Users/nikol/AppData/Roaming/.minecraft/mods/error-422-ported-0.1.0 (1).jar
	Failure message: ERROR 422 (error422) has failed to load correctly
		java.lang.Error: null
	Mod Version: 0.1.0
	Mod Issue URL: https://github.com/XyperCode/error-422-ported
	Exception message: java.lang.Error
Stacktrace:
	at io.github.xypercode.mods.err422.mixin.common.LoadingOverlayAccessor.setLogoBackgroundColor(LoadingOverlayAccessor.java:13) ~[error-422-ported-0.1.0%20(1).jar%23155!/:?] {re:classloading}
	at io.github.xypercode.mods.err422.client.Error422Client.init(Error422Client.java:12) ~[error-422-ported-0.1.0%20(1).jar%23155!/:?] {re:classloading}
	at io.github.xypercode.mods.err422.forge.Error422PortedForge.lambda$new$0(Error422PortedForge.java:21) ~[error-422-ported-0.1.0%20(1).jar%23155!/:?] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19.2-43.3.7.jar%23158!/:?] {}
	at io.github.xypercode.mods.err422.forge.Error422PortedForge.<init>(Error422PortedForge.java:20) ~[error-422-ported-0.1.0%20(1).jar%23155!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.2-43.3.7.jar%23159!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.2-43.3.7.jar%23158!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 216038488 bytes (206 MiB) / 469762048 bytes (448 MiB) up to 3657433088 bytes (3488 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.42
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1371
	Memory slot #0 capacity (MB): 1024.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 1024.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: LPDDR4
	Memory slot #2 capacity (MB): 1024.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: LPDDR4
	Memory slot #3 capacity (MB): 1024.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: LPDDR4
	Memory slot #4 capacity (MB): 1024.00
	Memory slot #4 clockSpeed (GHz): 3.20
	Memory slot #4 type: LPDDR4
	Memory slot #5 capacity (MB): 1024.00
	Memory slot #5 clockSpeed (GHz): 3.20
	Memory slot #5 type: LPDDR4
	Memory slot #6 capacity (MB): 1024.00
	Memory slot #6 clockSpeed (GHz): 3.20
	Memory slot #6 type: LPDDR4
	Memory slot #7 capacity (MB): 1024.00
	Memory slot #7 clockSpeed (GHz): 3.20
	Memory slot #7 type: LPDDR4
	Virtual memory max (MB): 21114.80
	Virtual memory used (MB): 10923.58
	Swap memory total (MB): 13180.48
	Swap memory used (MB): 951.72
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3480M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.3.7.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.7.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.3.7.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.3.7.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.7.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.19.2-43.3.7-universal.jar                 |Forge                         |forge                         |43.3.7              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		tl_skin_cape_forge_1.19_1.19.2-1.30.jar           |TLSkinCape                    |tlskincape                    |1.30                |COMMON_SET|Manifest: ef:fe:e7:59:91:bb:3a:06:c1:94:f4:f3:9c:3e:26:69:47:fa:2e:c5:53:d3:38:21:65:cc:04:75:e7:61:19:40
		error-422-ported-0.1.0 (1).jar                    |ERROR 422                     |error422                      |0.1.0               |ERROR     |Manifest: NOSIGNATURE
		architectury-6.6.92-forge.jar                     |Architectury                  |architectury                  |6.6.92              |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: c8567157-92d4-48b3-a2ea-21b83976a4f7
	FML: 43.3
	Forge: net.minecraftforge:43.3.7

**Comment by XyperCode** [comment]
Ok, no idea how this happened, but i seems like one of the mixins failed...

**Comment by ripgenius** [comment]
i cant play with this mod?

**Comment by XyperCode** [comment]
Um, you could try the Fabric version.

**Comment by ripgenius** [comment]
developer console

**Comment by ripgenius** [comment]
I entered into the game, but when the world load reaches 100, the game freezes and crashes with the developer console

**Comment by XyperCode** [comment]
```c++
#define developer_console
```

Seriously, not sure what you mean with developer console...

**Comment by ripgenius** [comment]
![Снимок экрана 2024-03-28 181101](https://github.com/Ultreon/ERROR422/assets/163667902/ecd20548-e2da-473b-88c4-633be5cc7355)

**Comment by ripgenius** [comment]
I have Russian language, so I took it from the Internet

**Comment by XyperCode** [comment]
Oh ok. A bit of a weird name to call it developer console (as "Console log" should fit better). Did you try with the Fabric version? So far I know the Forge version is broken at the moment.

I'm going to attempt to fix it but due the amount of projects and me being almost the only active developer it's quite hard to maintain everything.

**Comment by ripgenius** [comment]
![image](https://github.com/Ultreon/ERROR422/assets/163667902/17550d67-e624-4f3c-a9d4-1dda98be6e6f)
fabric💀

**Comment by XyperCode** [comment]
Issue related to: https://github.com/Ultreon/ultreonlib/issues/14
